# SecurityBundle
security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: %admin_password%, roles: ROLE_ADMIN }

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false
        wdt:
            pattern:  ^/_wdt
            security: false
        backend:
            pattern: ^/admin/
            http-basic: true
            logout:     true

    access_control:
        - { path: ^/admin/.*, role: ROLE_ADMIN }